export class Project {
    id:any;
    title:any;
    description:any;
    rate:any;
    budget:any;
    final_price:any;
    location:any;
    status:any;
    owner_id:any;
    developer_id:any;
    category_id:any;
    name:any;
    lname:any;
    image:any;
    type:any;
    email:any;
    cat_name:any;
    avatar:any;
    user_rate:any;
}
